"use client";

import {
  createContext,
  useContext,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { createTuningStore } from "./tuning-store";

/**
 * The project window: a case study opened beside the signs rather than
 * navigated to. The mechanics are meganyap.me's (looked at 2026-09-21):
 * the wall's left strip stays — the rail — and turns into the way home
 * plus the open page's table of contents, while the project takes the
 * rest of the screen. Here the rest is a sheet: full height, flush to
 * the top, right and bottom, white, square, a hairline down its left
 * edge, nothing dimmed behind it. The signs stay where they are in the
 * rail, over the sheet's edge, and are the switcher; the window knows
 * nothing about them — the caller keeps them above it (a z-index past
 * the window's 80) and tells the window how wide the rail is.
 *
 * The rail holds "Home" and a slot the page inside fills with its
 * contents (`useWindowRail()`); `foot` keeps both clear of whatever the
 * caller parks at the rail's bottom. The empty rail, Home, Esc and the
 * caller's own close all shut it. On a phone there is no rail:
 * the sheet is edge to edge and the slot is never filled.
 *
 * The sheet is the one thing here that eases: it slides in from the
 * right and out again, smoothly (Julio, 2026-09-21: in held cuts a
 * surface this big read as lag, not as stop motion). A switch swaps the
 * content at once, scrolled to the top, and the new page plays its own
 * entrances. `WindowTuning` is the set of knobs;
 * /lab/window is its bench, and <ProjectWindow> regenerates its
 * stylesheet on every change.
 *
 * The window is only the chrome: the page inside is the caller's
 * (`children`), which can find the sheet's scroller through
 * `useWindowScroller()` for anything scroll-driven.
 */

export type WindowTuning = {
  /** How long the slide in takes, ms; the slide out takes 0.7 of it. */
  duration: number;
  /** Where the sheet starts, to the right of its place, as a share of
   *  its own width, %. */
  distance: number;
  /** The rail's width, vw, when the caller does not give one. */
  rail: number;
  /** The hairline on the sheet's left edge, 0 to 1. */
  edge: number;
};

const WINDOW_DEFAULTS: Readonly<WindowTuning> = Object.freeze({
  duration: 420,
  distance: 100,
  rail: 27,
  edge: 0.16,
});

// ------------------------------------------------------------- the store

// A key of its own: the centred window's stored values meant other things.
const store = createTuningStore("sheet-tuning", WINDOW_DEFAULTS);

/** Lays `patch` over the current values and tells every subscriber. */
export const setWindowTuning = store.set;
export const resetWindowTuning = store.reset;
/** The live tuning, re-rendering the caller on every change. */
export const useWindowTuning = store.useTuning;

// -------------------------------------------------------- the stylesheet

/** The site's ink, for the controls; the rail's resting text. */
const MEDIUM = `var(--font-neue-montreal-extra), var(--font-neue-montreal), "Helvetica Neue", Arial, sans-serif`;
const INK = "#2b2722";
const FAINT = "#8a847c";
/** The controls' size. */
/** From this viewport width there is a rail; under it the sheet is the
 *  whole screen. */
const RAIL_FROM = 701;

const n = (v: number, d = 3) => Number(v.toFixed(d)).toString();

/** How long the slide out takes, ms. */
const exitMs = (t: WindowTuning) => t.duration * 0.7;

/** The whole stylesheet for a tuning. */
function windowCss(t: WindowTuning): string {
  const exit = exitMs(t);
  const d = t.distance;
  return `
/* the project window — generated by windowCss() from WindowTuning; edit on /lab/window */
.pw { --pw-rail: ${n(t.rail)}vw; --pw-inset: 24px; --pw-foot: 0px; position: fixed; inset: 0; z-index: 80; }
.pw-sheet { position: absolute; top: 0; right: 0; bottom: 0; left: 0; background: #fff; animation: pw-open ${n(t.duration, 0)}ms cubic-bezier(.22, 1, .36, 1) both; }
.pw-sheet:focus { outline: none; }
.pw-scroll { position: absolute; inset: 0; overflow-y: auto; overscroll-behavior: contain; }
/* The rail: the wall's left strip. Only what is in it takes the
   pointer; the rest of it is the way out. */
.pw-rail { display: none; }
@media (min-width: ${RAIL_FROM}px) {
  .pw-sheet { left: var(--pw-rail); border-left: 1px solid rgba(43, 39, 34, ${n(t.edge)}); }
  .pw-rail { display: block; position: absolute; top: 0; bottom: 0; left: 0; width: var(--pw-rail); }
  .pw-rail-in { position: absolute; top: 3.5vh; bottom: var(--pw-foot); left: var(--pw-inset); right: 20px; display: flex; flex-direction: column; align-items: flex-start; gap: 22px; overflow-y: auto; scrollbar-width: none; pointer-events: none; }
  .pw-rail-in::-webkit-scrollbar { display: none; }
  .pw-rail-in > * { flex: none; max-width: 100%; pointer-events: auto; }
  .pw-rail-slot:empty { display: none; }
}
/* Home: the way back to the projects, in the page's own type. */
.pw-home { display: inline-flex; align-items: center; gap: .5em; min-height: 24px; padding: 0; border: 0; background: none; color: ${FAINT}; font-family: ${MEDIUM}; font-weight: 500; font-size: 15px; line-height: 1; letter-spacing: -.01em; text-decoration: none; cursor: pointer; }
.pw-home:hover { color: ${INK}; }
.pw-home:focus-visible { outline: 2px solid #2f6df6; outline-offset: 4px; }
.pw-home svg { display: block; width: .8em; height: .8em; }
/* A page of its own (/work/<slug>): the sheet is simply there. */
.pw.is-page .pw-sheet { animation: none; }
/* Leaving: back out to the right; the rail empties at once. Plays
   while the window is still mounted. */
.pw.is-leaving .pw-sheet { animation: pw-exit ${n(exit, 0)}ms cubic-bezier(.55, 0, .8, .4) both; }
.pw.is-leaving .pw-rail-in { visibility: hidden; }
@keyframes pw-open { from { transform: translateX(${n(d)}%); } to { transform: none; } }
@keyframes pw-exit { from { transform: none; } to { transform: translateX(${n(d)}%); } }
@media (prefers-reduced-motion: reduce) {
  .pw-sheet, .pw.is-leaving .pw-sheet { animation-duration: 1ms; }
}
`;
}

// ------------------------------------------------------------- the sounds

/** The site's sounds, fetched on demand: the landing has them already,
 *  and a project page of its own (/work/<slug>) is at the first-load
 *  budget without the synth — it warms them on mount and plays the
 *  first click from the cache. */
const sounds = () => import("./sound");

function click(name: "tap" | "knock") {
  void sounds().then((m) => m.play(name, 1, { at: "click" }));
}

// ------------------------------------------- the scroller and the rail

const ScrollerContext = createContext<HTMLElement | null>(null);
const RailContext = createContext<HTMLElement | null>(null);

/** The sheet's scroller, for the page inside the window — the root for
 *  anything that watches the scroll. Null before the sheet mounts. */
export function useWindowScroller(): HTMLElement | null {
  return useContext(ScrollerContext);
}

/** The rail's slot, under Home: the page inside portals its contents
 *  into it. Null before the window mounts, and outside a window; on a
 *  phone it is there but never shown. */
export function useWindowRail(): HTMLElement | null {
  return useContext(RailContext);
}

// ------------------------------------------------------------- the icons

const ARROW_LEFT = (
  <svg viewBox="0 0 12 12" fill="none" aria-hidden="true">
    <path
      d="M7.5 1.5 3 6l4.5 4.5M3 6h8"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="square"
    />
  </svg>
);

// --------------------------------------------------------- the component

/** Where the rail's things go, as CSS lengths — the caller's, since
 *  they follow what it keeps in the rail. */
export type WindowLayout = {
  /** The rail's width: where the sheet's left edge is. */
  rail?: string;
  /** The rail's content, from the screen's left edge. */
  inset?: string;
  /** Kept free at the rail's bottom. */
  foot?: string;
};

type ProjectWindowProps = {
  /** The open project's slug: a change starts the next page at its top. */
  active: string;
  /** Flip to false to close: the exit plays, then the window unmounts
   *  itself. */
  shown: boolean;
  /** "modal" (default): over the page, with the entrance; Home and the
   *  empty rail ask to close — on the landing, a step back in the
   *  history, to the projects. "page": the window is the page — no
   *  entrance; Home is a link to `closeHref`. */
  mode?: "modal" | "page";
  /** For the dialog's name: the open project's title. */
  label: string;
  layout?: WindowLayout;
  /** Page mode: where Home goes — the projects. */
  closeHref?: string;
  /** Modal mode: the window asks to close. */
  onClose?: () => void;
  children?: ReactNode;
};

/**
 * The sheet, the rail and the controls. The page inside is `children`;
 * on a switch it is up to the caller to render the next page (keyed, so
 * its entrances play) — the window scrolls back to the top. Focus goes
 * to the sheet on open and back where it was on close; the page behind
 * stops scrolling while the window is up.
 */
export function ProjectWindow({
  active,
  shown,
  mode = "modal",
  label,
  layout,
  closeHref,
  onClose,
  children,
}: ProjectWindowProps) {
  const t = useWindowTuning();
  const page = mode === "page";
  const [scroller, setScroller] = useState<HTMLElement | null>(null);
  const [rail, setRail] = useState<HTMLElement | null>(null);
  const sheet = useRef<HTMLDivElement>(null);

  // Derived during render, the cue's way: a flip to hidden starts the
  // exit, which keeps the window mounted while it slides out.
  const [prevShown, setPrevShown] = useState(shown);
  const [leaving, setLeaving] = useState(false);
  if (shown !== prevShown) {
    setPrevShown(shown);
    setLeaving(!shown);
  }
  const exit = exitMs(t);
  useEffect(() => {
    if (!leaving) return;
    const id = window.setTimeout(() => setLeaving(false), exit);
    return () => window.clearTimeout(id);
  }, [leaving, exit]);

  const mounted = shown || leaving;

  // The page behind holds still, Esc closes, and focus is kept: on the
  // sheet while the window is up, back where it was after.
  useEffect(() => {
    if (!mounted || page) return;
    const root = document.documentElement;
    const was = root.style.overflow;
    root.style.overflow = "hidden";
    const before = document.activeElement as HTMLElement | null;
    sheet.current?.focus({ preventScroll: true });
    return () => {
      root.style.overflow = was;
      before?.focus?.({ preventScroll: true });
    };
  }, [mounted, page]);
  useEffect(() => {
    if (!shown || page) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        onClose?.();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [shown, page, onClose]);

  // A switch starts the next page at its top.
  useEffect(() => {
    if (scroller) scroller.scrollTop = 0;
  }, [active, scroller]);
  useEffect(() => {
    void sounds();
  }, []);

  if (!mounted) return null;

  const close = () => {
    click("knock");
    onClose?.();
  };
  const vars = {
    ...(layout?.rail && { "--pw-rail": layout.rail }),
    ...(layout?.inset && { "--pw-inset": layout.inset }),
    ...(layout?.foot && { "--pw-foot": layout.foot }),
  } as CSSProperties;

  return (
    <div
      className={["pw", page && "is-page", leaving && "is-leaving"]
        .filter(Boolean)
        .join(" ")}
      style={vars}
    >
      <style>{windowCss(t)}</style>
      <div
        className="pw-rail"
        data-cursor-label={page ? undefined : "close"}
        onClick={(e) => {
          if (!page && e.target === e.currentTarget) close();
        }}
      >
        <div className="pw-rail-in">
          {page && closeHref ? (
            <a href={closeHref} className="pw-home" data-cursor-label="home">
              {ARROW_LEFT}
              Home
            </a>
          ) : (
            <button
              type="button"
              className="pw-home"
              data-cursor-label="home"
              onClick={close}
            >
              {ARROW_LEFT}
              Home
            </button>
          )}
          <div ref={setRail} className="pw-rail-slot" />
        </div>
      </div>
      <div
        ref={sheet}
        className="pw-sheet"
        role="dialog"
        aria-label={label}
        tabIndex={-1}
      >
        <div ref={setScroller} className="pw-scroll">
          <ScrollerContext.Provider value={scroller}>
            <RailContext.Provider value={rail}>{children}</RailContext.Provider>
          </ScrollerContext.Provider>
        </div>
      </div>
    </div>
  );
}
